BASELINE_GUITAR_DIFFS = {
    "System of a Down - A.D.D. (Wagsii)": 3,
    "System of a Down - Aerials (Harmonix)": 3,
    "System of a Down - Arto (Wagsii)": 1,
    "System of a Down - Attack (Wagsii)": 4,
    "System of a Down - ATWA (Wagsii)": 0,
    "System of a Down - B.Y.O.B. (Harmonix)": 5,
    "System of a Down - Blue (Wagsii)": 1,
    "System of a Down - Boom (Wagsii)": 4,
    "System of a Down - Bounce (thardwardy)": 1,
    "System of a Down - Bubbles (thardwardy)": 2,
    "System of a Down - Cherry (Wagsii)": 3,
    "System of a Down - Chic N Stu (Wagsii)": 3,
    "System of a Down - Chop Suey (Harmonix)": 5,
    "System of a Down - Cigaro (Debugmod12)": 4,
    "System of a Down - CUBErt (Wagsii)": 2,
    "System of a Down - Dam (Wagsii)": 0,
    "System of a Down - Darts (thardwardy)": 1,
    "System of a Down - DDevil (Wagsii)": 5,
    "System of a Down - Deer Dance (Wagsii)": 2,
    "System of a Down - Dreaming (Wagsii)": 4,
    "System of a Down - Ego Brain (MercuryHg34)": 2,
    "System of a Down - Forest (Wagsii)": 2,
    "System of a Down - Fortress Outer Space (Wagsii)": 3,
    "System of a Down - Friik (Wagsii)": 5,
    "System of a Down - Fuck the System (Tris255)": 3,
    "System of a Down - Genocidal Humanoidz (K4JK0)": 4,
    "System of a Down - Highway Song (Wagsii)": 3,
    "System of a Down - Holy Mountains (Wagsii)": 3,
    "System of a Down - Honey (Wagsii)": 3,
    "System of a Down - Hypnotize (Harmonix)": 3,
    "System of a Down - I-E-A-I-A-I-O (TheZombieDon (Trickii))": 4,
    "System of a Down - Innervision (Wagsii)": 3,
    "System of a Down - Jet Pilot (Wagsii)": 4,
    "System of a Down - Johnny (Wagsii)": 2,
    "System of a Down - Kill Rock n' Roll (Wagsii)": 2,
    "System of a Down - Know (Wagsii)": 3,
    "System of a Down - Lonely Day (thardwardy)": 4,
    "System of a Down - Lost In Hollywood (Wagsii)": 2,
    "System of a Down - Marmalade (thardwardy)": 2,
    "System of a Down - Mind (Wagsii)": 4,
    "System of a Down - Mr. Jack (Wagsii)": 2,
    "System of a Down - Needles (thardwardy)": 2,
    "System of a Down - Nuguns (Wagsii)": 3,
    "System of a Down - Old School Hollywood (Wagsii)": 3,
    "System of a Down - P.L.U.C.K. (Wagsii)": 4,
    "System of a Down - Pictures (Wagsii)": 3,
    "System of a Down - Prison Song (Wagsii)": 1,
    "System of a Down - Protect The Land (Wagsii)": 2,
    "System of a Down - Psycho (Wagsii)": 2,
    "System of a Down - Question (Wagsii)": 4,
    "System of a Down - Radio Video (Wagsii)": 2,
    "System of a Down - Revenga (Wagsii)": 4,
    "System of a Down - Roulette (Wagsii)": 1,
    "System of a Down - Sad Statue (Wagsii)": 4,
    "System of a Down - Science (Wagsii)": 2,
    "System of a Down - She's Like Heroin (Wagsii)": 2,
    "System of a Down - Shimmy (oldfashionedman)": 2,
    "System of a Down - Soil (Wagsii)": 5,
    "System of a Down - Soldier Side (thardwardy)": 2,
    "System of a Down - Spiders (Harmonix)": 1,
    "System of a Down - Stealing Society (Wagsii)": 4,
    "System of a Down - Storaged (thardwardy)": 3,
    "System of a Down - Streamline (Wagsii)": 3,
    "System of a Down - Sugar (Wagsii)": 4,
    "System of a Down - Suggestions (Wagsii)": 3,
    "System of a Down - Suite-Pee (Peddy)": 2,
    "System of a Down - Temper (Wagsii)": 2,
    "System of a Down - Tentative (Wagsii)": 3,
    "System of a Down - The Metro (Berlin Cover) (thardwardy)": 1,
    "System of a Down - Thetawaves (Wagsii)": 4,
    "System of a Down - This Cocaine Makes Me Feel Like I'm On This Song (Wagsii)": 4,
    "System of a Down - Toxicity (Harmonix)": 4,
    "System of a Down - U-Fig (Wagsii)": 3,
    "System of a Down - Vicinity of Obscenity (Halcyon)": 0,
    "System of a Down - Violent Pornography (Nyoxide, blitzbob, sailingwhisper, Toppin)": 3,
    "System of a Down - War (Wagsii)": 4,
    "System of a Down - X (thardwardy)": 2,
}

BASELINE_DRUM_DIFFS = {
    "System of a Down - Aerials (Harmonix)": 4,
    "System of a Down - B.Y.O.B. (Harmonix)": 5,
    "System of a Down - Bounce (thardwardy)": 2,
    "System of a Down - Bubbles (thardwardy)": 2,
    "System of a Down - Chop Suey (Harmonix)": 4,
    "System of a Down - Cigaro (Debugmod12)": 5,
    "System of a Down - Hypnotize (Harmonix)": 4,
    "System of a Down - Lonely Day (thardwardy)": 1,
    "System of a Down - Marmalade (thardwardy)": 2,
    "System of a Down - Needles (thardwardy)": 3,
    "System of a Down - Spiders (Harmonix)": 2,
    "System of a Down - Storaged (thardwardy)": 3,
    "System of a Down - The Metro (Berlin Cover) (thardwardy)": 2,
    "System of a Down - Toxicity (Harmonix)": 5,
    "System of a Down - Vicinity of Obscenity (Halcyon)": 5,
    "System of a Down - X (thardwardy)": 3,
}

MANUAL_GUITAR_OVERRIDES = {
    "System of a Down - Arto (Wagsii)": 1,
    "System of a Down - Dam (Wagsii)": 1,
    "System of a Down - Roulette (Wagsii)": 1,
    "System of a Down - ATWA (Wagsii)": 4,
    "System of a Down - Vicinity of Obscenity (Halcyon)": 5,
}

MANUAL_DRUM_OVERRIDES = {
    "System of a Down - Soil (Wagsii)": 6,
}

MANUAL_VOCAL_OVERRIDES = {
    "System of a Down - Aerials (Harmonix)": 3,
    "System of a Down - B.Y.O.B. (Harmonix)": 5,
    "System of a Down - Chop Suey (Harmonix)": 6,
    "System of a Down - Hypnotize (Harmonix)": 4,
    "System of a Down - Spiders (Harmonix)": 5,
    "System of a Down - Toxicity (Harmonix)": 6,
}

GUITAR_SCALE_MAPPING = {
    1: 2,
    2: 3,
    3: 4,
    4: 5,
    5: 6,
}

